name: Image Sync

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: 'Source container image to sync (e.g., nginx:latest, ubuntu:20.04)'
        required: true
      target_org:
        description: 'Target organization in GHCR (default: current repository owner)'
        required: false
        default: ${{ github.repository_owner }}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Set GITHUB_ACTOR environment variable explicitly
      - name: Set GITHUB_ACTOR
        run: echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV

      - name: Build image-syncer
        run: |
          go build -o image-syncer ./cmd/image-syncer

      - name: Sync image
        run: |
          TARGET_ORG="${{ github.event.inputs.target_org }}"
          if [ -z "$TARGET_ORG" ]; then
            TARGET_ORG="${{ github.repository_owner }}"
          fi
          
          ./image-syncer \
            -source "${{ github.event.inputs.source_image }}" \
            -target-org "$TARGET_ORG" \
            -token "${{ secrets.GITHUB_TOKEN }}"