name: Test

on:
  push:
    branches: [ main, test-* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Run unit tests
        run: |
          go test -coverprofile=coverage.out -v ./...
          go tool cover -func=coverage.out

      - name: Build
        run: go build -v ./cmd/image-syncer

      - name: Test CLI (basic validation)
        run: |
          # Test with missing arguments (should fail)
          if ./image-syncer 2>&1 | grep -q "source image, target organization, and GHCR token are required"; then
            echo "CLI validation test passed"
          else
            echo "CLI validation test failed"
            exit 1
          fi